export const types = {
   fire: '#EE8130',
   electric: '#F7D02C',
   water: '#6390F0',
   grass: '#7AC74C',
   fighting: '#C22E28',
   flying: '#A98FF3',
   steel: '#B7B7CE',
   rock: '#B6A136',
};

export const pokemons = [
   {
      name: 'Aggron',
      level: '84',
      types: [types.steel, types.rock],
      trainer: 'Aurora Skyheart',
      image: './assets/aggron.png',
      mega: true,
      legendary: false,
      starter: false,
   },
   {
      name: 'Toxtricity',
      level: '41',
      types: [types.electric],
      trainer: 'Ashlyn Shadowcaster',
      image: './assets/toxtricity.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Ferrothorn',
      level: '70',
      types: [types.grass, types.steel],
      trainer: 'Aurora Skyheart',
      image: './assets/ferrothorn.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Turtwig',
      level: '14',
      types: [types.grass],
      trainer: 'Ivy Whisperleaf',
      image: './assets/turtwig.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Terrakion',
      level: '60',
      types: [types.fighting, types.rock],
      trainer: 'Lily Shadow',
      image: './assets/terrakion.png',
      mega: false,
      legendary: true,
      starter: false,
   },
   {
      name: 'Sceptile',
      level: '38',
      types: [types.grass],
      trainer: 'Flint Raptor',
      image: './assets/sceptile.png',
      mega: true,
      legendary: false,
      starter: true,
   },
   {
      name: 'Infernape',
      level: '56',
      types: [types.fire, types.fighting],
      trainer: 'Axel Emberstrike',
      image: './assets/infernape.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Pikachu',
      level: '27',
      types: [types.electric],
      trainer: 'Flint Raptor',
      image: './assets/pikachu.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Empoleon',
      level: '72',
      types: [types.water, types.steel],
      trainer: 'Flint Raptor',
      image: './assets/empoleon.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Ho-oh',
      level: '90',
      types: [types.fire, types.flying],
      trainer: 'Axel Emberstrike',
      image: './assets/hooh.png',
      mega: false,
      legendary: true,
      starter: false,
   },
];
