export const types = {
   fire: '#EE8130',
   electric: '#F7D02C',
   water: '#6390F0',
   grass: '#7AC74C',
   fighting: '#C22E28',
   flying: '#A98FF3',
   steel: '#B7B7CE',
   rock: '#B6A136',
};

export const pokemons = [
   {
      name: 'Aggron',
      level: '84',
      types: [types.steel, types.rock],
      trainer: 'Aurora Sky',
      image: './assets/aggron.png',
      mega: true,
      legendary: false,
      starter: false,
   },
   {
      name: 'Toxtricity',
      level: '41',
      types: [types.electric],
      trainer: 'Ashlyn Shadow',
      image: './assets/toxtricity.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Ferrothorn',
      level: '70',
      types: [types.grass, types.steel],
      trainer: 'Aurora Sky',
      image: './assets/ferrothorn.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Turtwig',
      level: '14',
      types: [types.grass],
      trainer: 'Ivy Whisper',
      image: './assets/turtwig.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Terrakion',
      level: '60',
      types: [types.fighting, types.rock],
      trainer: 'Lily Shadow',
      image: './assets/terrakion.png',
      mega: false,
      legendary: true,
      starter: false,
   },
   {
      name: 'Sceptile',
      level: '38',
      types: [types.grass],
      trainer: 'Flint Raptor',
      image: './assets/sceptile.png',
      mega: true,
      legendary: false,
      starter: true,
   },
   {
      name: 'Infernape',
      level: '56',
      types: [types.fire, types.fighting],
      trainer: 'Axel Ember',
      image: './assets/infernape.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Pikachu',
      level: '27',
      types: [types.electric],
      trainer: 'Flint Raptor',
      image: './assets/pikachu.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Empoleon',
      level: '72',
      types: [types.water, types.steel],
      trainer: 'Flint Raptor',
      image: './assets/empoleon.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Ho-oh',
      level: '90',
      types: [types.fire, types.flying],
      trainer: 'Axel Ember',
      image: './assets/hooh.png',
      mega: false,
      legendary: true,
      starter: false,
   },
   {
      name: 'Breloom',
      level: '53',
      types: [types.grass, types.fighting],
      trainer: 'Flint Raptor',
      image: './assets/breloom.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Tepig',
      level: '6',
      types: [types.fire],
      trainer: 'Aurora Sky',
      image: './assets/tepig.png',
      mega: false,
      legendary: false,
      starter: true,
   },
   {
      name: 'Entei',
      level: '60',
      types: [types.fire],
      trainer: 'Lily Shadow',
      image: './assets/entei.png',
      mega: false,
      legendary: true,
      starter: false,
   },
   {
      name: 'Vaporeon',
      level: '47',
      types: [types.water],
      trainer: 'Ashlyn Shadow',
      image: './assets/vaporeon.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Ampharos',
      level: '63',
      types: [types.electric],
      trainer: 'Axel Ember',
      image: './assets/ampharos_mega.png',
      mega: true,
      legendary: false,
      starter: false,
   },
   {
      name: 'Hawlucha',
      level: '18',
      types: [types.flying, types.fighting],
      trainer: 'Lily Shadow',
      image: './assets/hawlucha.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Kabutops',
      level: '36',
      types: [types.rock],
      trainer: 'Ivy Whisper',
      image: './assets/kabutops.png',
      mega: false,
      legendary: false,
      starter: false,
   },
   {
      name: 'Registeel',
      level: '90',
      types: [types.steel],
      trainer: 'Ivy Whisper',
      image: './assets/registeel.png',
      mega: false,
      legendary: true,
      starter: false,
   },
   {
      name: 'Onix',
      level: '63',
      types: [types.rock],
      trainer: 'Aurora Sky',
      image: './assets/onix.png',
      mega: true,
      legendary: false,
      starter: false,
   },
   {
      name: 'Gyarados',
      level: '71',
      types: [types.water, types.flying],
      trainer: 'Ashlyn Shadow',
      image: './assets/gyarados.png',
      mega: true,
      legendary: false,
      starter: false,
   },
];
